Javascript課題➂－１実施
keiKunn/JS_practice pull request #7
Opened 2020-11-16 03:26 UTC by keiKunn

- 実装の概要
タスク(ID、コメント、状態)をテーブルタグで表示する。
また、上記のタスクはオブジェクトに格納して管理する。
入力フォームに値が入力された場合、テーブルタグの追加処理を行う。

- レビュー頂きたい点
①td要素の有無によって既存タスクがあるかどうかの条件分けを行いましたが、判定式の使い方として正しいでしょうか。
４６行目：`if (cells.length !== 0) {`

（file changedの行番号をクリックしても、ソースリンクが貼れなかったため手動で残しました。プルリク作成時のコメントでは貼れなさそうなんでしょうか...）

②以下内容は、後続課題でのタスク状態切り替え機能の実装を予想してidプロパティを追加しました。（状態ボタン押下時に、どの行のどのセルかを判別する必要があるかなと考えたためです）
必要なさそうであれば、ご指摘頂きたいです。
５３行目 / `status: '<input type="button" id="workButtonId_' + (taskTable.rows.length) + '" value="作業中"> <input type="button" id="deleteButtonId_' + (taskTable.rows.length) + '" value="削除">'`

以上、宜しくお願い致します。

2020-11-17 12:42 UTC, myzktkyk requested changes
1点指摘をしております。

2020-11-17 12:42 UTC, myzktkyk commented on index3_1.html
> +          let taskObj = [];
>また、上記のタスクはオブジェクトに格納して管理する。

この行が上記の仕様と対応するように見えるのですが、これだと管理にはなっていないと思います。

- このコードでは空の配列に初期化されてしまう
  - 空になってしまうのでは「管理」していることにならないのでは？と思います
- 本当に「管理」するのであれば、スクが追加されるたびに配列にオブジェクトが追加されて保持されるようにしないとダメだと思います

2020-11-17 15:27 UTC, keiKunn commented on index3_1.html
> +          let taskObj = [];
レビュ―頂きありがとうございます。
最新コミットにて以下の修正を行いました

- タスク格納オブジェクトをクリックイベントから外だし
https://github.com/keiKunn/JS_practice/blob/7a5342b4305dca27197ff8362ab9e479fc6c8c66/index3_1.html#L40

- タスク格納オブジェクトのサイズで、新規追加or追加を判定
https://github.com/keiKunn/JS_practice/blob/7a5342b4305dca27197ff8362ab9e479fc6c8c66/index3_1.html#L47

- 既存タスクがある場合に、追加タスクのみを表示させるため`addTaskObj`を表示処理に使用
https://github.com/keiKunn/JS_practice/blob/7a5342b4305dca27197ff8362ab9e479fc6c8c66/index3_1.html#L56-L58

2020-11-19 00:31 UTC, kouki-iwahara reviewed
コメントしましたのでご確認ください！

2020-11-19 00:31 UTC, kouki-iwahara commented on index3_1.html
> +  <script>
今回から記述量が増えてきますので、jsは別ファイルで記述しhtml側で読み込むと良いです。

2020-11-19 00:31 UTC, kouki-iwahara commented on index3_1.html
> +      const inputTask = document.getElementById('addForm').value;
ここの処理内容を、addTodoなどのような名前をつけて関数化し、クリックイベント時に呼び出す設計が望ましいです。

2020-11-19 00:31 UTC, kouki-iwahara commented on index3_1.html
> +      if (inputTask.trim()) {
空のまま追加させないような条件かと思いますが、異常系の条件（空のまま追加される条件）を先に記述し、if文をすぐ閉じる設計の方が可読性が高いです。
今回ですと、
```
if(!inputTask.trim()) {
　処理内容
　return
}
const taskTable = document.getElementById('taskTableId');
,,,,,,
```
のようなイメージです。

2020-11-19 00:31 UTC, kouki-iwahara commented on index3_1.html
> +    let taskObj = [];
constで定義できます。
再代入される場合はlet、されない場合はconstです。
また、名前はobjというオブジェクトを連想させる単語ですが、実際は配列が定義されているので違和感ですね。
配列を定義したいのであれば、複数形の単語を使用して
tasksやtodosという名前が良いと思います。

2020-11-19 00:31 UTC, kouki-iwahara commented on index3_1.html
> +            status: '<input type="button" id="workButtonId_' + (taskTable.rows.length) + '" value="作業中"> <input type="button" id="deleteButtonId_' + (taskTable.rows.length) + '" value="削除">'
ボタン生成に関して
これですとただの文字列の扱いになってしまい、jsでの操作が難しくなります。
なので、createElementを使用して要素を生成しましょう。
https://developer.mozilla.org/ja/docs/Web/API/Document/createElement

また、この生成に関する記述は関数で切り分けると良いです。
現在ですと、追加ボタンを押した際に様々な目的の処理が記載されているので、目的ごとに関数に切り分けましょう。

2020-11-19 00:31 UTC, kouki-iwahara commented on index3_1.html
> +          // 追加済タスクが存在しない場合、入力値でオブジェクトを生成する
この条件分岐は、追加済タスクが存在しない場合、idを0にしたいという意図だと思うので、オブジェクト生成時に以下のようにすると、このelse文が削除できすっきり記述できます。

```
const newTaskObj = {
      id: !taskTable.rows.length ? 0 : taskTable.rows.length - 1,
      ,,,,,,,
}
```

2020-11-19 00:31 UTC, kouki-iwahara commented on index3_1.html
> +          displayTask(taskTable, addTaskObj);
`const addTaskObj = [newTaskObj];`
としてから
`displayTask(taskTable, addTaskObj);`
とされていますが、どのような意図でしょうか？
54行目の`taskObj.push(newTaskObj);`
で配列にnewTaskObjを追加していると思うのですが、現在の実装ですとこの54行目のコードの意味がなくなってしまいます。
何かやりたいことがあるのであればご相談いただければアドバイスできます。

2020-11-19 00:31 UTC, kouki-iwahara commented on index3_1.html
> +      taskObj.map(function (obj) {
mapは配列を返却する関数ですので、今回はその返却値を使用していないことから、forEachを使用すると良いです。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

2020-11-19 00:31 UTC, kouki-iwahara commented on index3_1.html
> +  <div id="radioAreaId">
htmlではキャメルケースは使わずにハイフンや場合によりアンスコで単語を繋ぐのが一般的です。

2020-11-19 00:31 UTC, kouki-iwahara commented on index3_1.html
> +        if (taskObj.length !== 0) {
条件を以下のように記述できます。
`if (taskObj.length) {}`

2020-11-19 05:29 UTC, keiKunn commented on index3_1.html
> +          displayTask(taskTable, addTaskObj);
`taskObj`に格納されているオブジェクト数分、`displayTask()`を呼び出す作りにしていたため、追加分タスク(addTaskObj )のみを渡してあげないと既存タスクが２重で表示されてしまうためです。
※今回の最新コミットで、表示処理のフローを変更したため、上記処理は無くなりました。

2020-11-19 05:30 UTC, keiKunn commented on index3_1.html
> +  <script>
反映しました。

2020-11-19 05:30 UTC, keiKunn commented on index3_1.html
> +      const inputTask = document.getElementById('addForm').value;
反映しました。

2020-11-19 05:43 UTC, keiKunn commented on index3_1.html
> +  <div id="radioAreaId">
修正しました。
vscode上で既存変数名の変更を行う際に、別ファイルも含めて一括置換をすることはできるのでしょうか。
(同一ファイル内であれば、同変数名を一括置き換えできますが、今回のように外部ファイルの場合は、手動でファイル全検索かけて該当箇所を一か所ずつ置き換えないといけない？)

2020-11-19 05:50 UTC, keiKunn commented on index3_1.html
> +      taskObj.map(function (obj) {
承知しました。
最新コミット分の修正で、繰り返し処理が不要になりました。

2020-11-19 05:51 UTC, keiKunn commented on index3_1.html
> +        if (taskObj.length !== 0) {
承知しました。
最新コミット分で不要な判定処理になりましたので、削除しました。

2020-11-19 05:52 UTC, keiKunn commented on index3_1.html
> +          // 追加済タスクが存在しない場合、入力値でオブジェクトを生成する
反映しました。

2020-11-19 05:54 UTC, keiKunn commented on index3_1.html
> +            status: '<input type="button" id="workButtonId_' + (taskTable.rows.length) + '" value="作業中"> <input type="button" id="deleteButtonId_' + (taskTable.rows.length) + '" value="削除">'
反映しました。

2020-11-19 05:54 UTC, keiKunn commented on index3_1.html
> +      if (inputTask.trim()) {
反映しました。

2020-11-19 06:29 UTC, keiKunn commented
レビュー頂きありがとうございます。
１点、２時間以上解決目途が立てられなかった箇所があるためご教授頂けますでしょうか。

今回のレビュー(https://github.com/keiKunn/JS_practice/pull/7#discussion_r526508604)で　ボタンのinputタグを`createElement`で設定するようにしましたが、表示処理時に`[object HTMLInputElement]`と表示されてしまいます。
他、tdセルに`appendChild`する形で考えましたが、実行エラー`Uncaught TypeError`となりました。
https://github.com/keiKunn/JS_practice/blob/ab5b3c0495361aa628de808455d24498dfecb34a/js/index3_1.js#L65-L69

・試したこと
「object HTMLinputelement 出力」などのキーワードで検索
→解決につながる情報が得られない。HTMLinputelement ではなく、innertHTMLを使用してinputタグを出力するケースが多い。
・MDNでHTMLInputElementの仕様を確認→`newCell.innerHTML = newStatus.value`を試すが`undefined`が取得される。
https://developer.mozilla.org/ja/docs/Web/API/HTMLInputElement

以上、宜しくお願い致します。

2020-11-20 09:11 UTC, kouki-iwahara commented
innerHTMLはマークアップを取得したり設定したりするメソッドですが、そのメソッドにボタン要素を設定しているため、表示処理時に[object HTMLInputElement]と表示されているのだと思います。
なので少し設計を変更して、taskのstatusをボタン要素ではなく文字列（'作業中'など）にすると良いかと思います！

2020-11-20 15:24 UTC, keiKunn commented
こういうことではなかったのかなと自信がありませんが、ご確認の程お願い致します。
以下の通り変更しました。

taskのstatusを文字列に変更
↓
`displayTask()`で作業中ボタン・削除ボタンををinnerHTMLで生成。
https://github.com/keiKunn/JS_practice/blob/024387b17323b55ce8bc9e4769fa5e6bdfc739db/js/index3_1.js#L69-L76

上記の実装ですと、過去レビュー(https://github.com/keiKunn/JS_practice/pull/7#discussion_r526508604)
の内容を反映した`addTaskBtn(row)`の関数を使うことがなくなります。(createElementを使ったボタン生成を行わない)

個人的にはaddTaskBtn(row)で生成したinput要素を、innerHTML以外の方法で追加できればスッキリするとは思っているのですが、難しいのでしょうか。
（`newCell.appendChild(newStatus);`は実行エラーとなる）

2020-11-23 01:18 UTC, kouki-iwahara reviewed
コメントしましたのでご確認ください。

2020-11-23 01:18 UTC, kouki-iwahara commented on js/index3_1.js
> +    return false;
処理を止めるだけでしたらfalseは省略できます。

2020-11-23 01:18 UTC, kouki-iwahara commented on js/index3_1.js
> +    delete: '削除'
deleteは「削除」という文字列から変わらないため、値を管理する必要はないです。

2020-11-23 01:18 UTC, kouki-iwahara commented on js/index3_1.js
> +  newCell.innerHTML =`<input type='button' id='workBtn_${taskTable.rows.length-1}' value='${newStatus}'>`
innerHTMLで要素を作成しても文字列の扱いなので、jsでの操作がしにくくなります。
なので、
・createElementでボタン要素を生成
・生成したボタンのテキストをtaskのstatusにする
・それをappendChildで追加
という実装が良いと思います。
コメントアウトされているaddTaskBtn関数の処理内容に近いですね。

2020-11-23 02:42 UTC, keiKunn commented on js/index3_1.js
> +    return false;
反映しました。

2020-11-23 02:43 UTC, keiKunn commented on js/index3_1.js
> +    delete: '削除'
反映しました。

2020-11-23 03:22 UTC, keiKunn commented on js/index3_1.js
> +  newCell.innerHTML =`<input type='button' id='workBtn_${taskTable.rows.length-1}' value='${newStatus}'>`
以下の修正にて反映しました。
https://github.com/keiKunn/JS_practice/blob/b8fcd8d7c62f45555f1797332dcfe32949ed6a88/js/index3_1.js#L48-L62

オブジェクトへ要素を格納して、それを一気にappendChildすることは難しいのかなと理解しました。

2020-11-24 00:28 UTC, merged